spring:
  datasource:
    url: jdbc:postgresql://secure-api-db.cbg4ma8ggmkj.us-east-2.rds.amazonaws.com:5432/secureapi?sslmode=require
    username: postgres
    password: "123One23$"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: adsjfdff

server:
  port: 8080